dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: lucacappelletti94-github
    token:
      secure: jcIxIppnYNJBeV4vUCDR8oDvx8fCkbfmgjN0c3gONMOzCemFpZ89H5DGArEGO9XJI9RAzwSx2rayzgpMsMgXDfMdbvqBhvbCmhptcLQKfRpGVrvEom/QNB0Zlbkn9K0sTRpjkq37/al696z9wX1G095/VZI0XTH9ZNMJ7uiRKRkd5Yc/sp8aEkMXpUm/dOd7G0Zbq92B+UkyWWSoa0nOIYqe0moOFbV4n4mj/J3xXqyPYUdTwpmj7E4YimkAN5+6sZhjDbCc8VdFKn0amRSqYtWNU0owR6yO3MeH++rGleA6xRHsNAoHWhx1+mKekOzviuRXw6Ebkcl+XFCWgMoDFwcT/6ZcschWUKF6zbG4TA7vUwFG8iHIZU/B6FMyQ96dj2To44O3FRK7dT1f3kmbfn1hNXfsjAikkkBjh7YfM2dUGiRUC8jQdKk5V/3H3a3fDYLpqKA3do3MX0/znG0/+LKvyu9EFTNE82CNYRKg7VNZgVrAosZQ7ALmjepK+NKbb9TqoGqm8UY2i+o5Y/RdDr8VRwH3zM3W/0IR/0mYERtvrjhQgOv4IfVg/F2UWpKw3aOZv5U+q9yYW7igXbTx+rIjdbm4t4NiWieH3E2Iz8vlRa6kYpUxWH0iN9Y/zlzK1vFLlmnEYI16O+kfbRX3PjAdrCQV4Ft+6rMc9bZt6Gg=
language: python
python:
- '3.6'
before_install:
- pip install --upgrade pytest
install:
- pip install .[test]
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=plot_keras_history --cov-report xml:coverage.xml
- coverage combine --append || true
- coverage report
- coverage xml
- sonar-scanner
after_success:
- coveralls
- python-codacy-coverage -r coverage.xml
env:
  global:
  - secure: rGax+WDmB1PRfhsQmcJ/bWyKmDQtGbEXD/ANvENbJaAPOAgUNcBR3KlFZOB1SBd9LhCusxNkPWenxZi6DT1lPuhxXpP7t/nhY804mx73vFAIrOQCw9yZVp0f0mwUuRFGc76BTbRnoGq215s1T2I3pdCDyPrbFx6Sq0D2h66wrF0S/b2cKBIvvOm39HxYLoxt22NaHYf6mn+xwF8RMrKRThBKdqLiJD4NIx4mXcRRZKKMCVNd4iDTxtX50m5w3MUDBlxecZAX2KlnQjYRjSpzTf7bHJk0SpPuChQrq5auuL7bBlnly4EYgwfQwBEghuZ/q+F03wO4amGNmVXlTm5PgVpDfZrulZpBLjWa385dqr/APKapa9+CP9Btch5gR2Lwlrr6bmap5sj+ZAxEFGxqBxO4krt13IMI9NM1Dujo6tXtNzF1q5u7R30GEQPNeQj4O6sd22gh5x61F/6iu8Qucuk6pNOMVk1aSksEUQ1XislQg9TAknaVEpUlhcqu6S8Zx/4z4nzlJm6Hut392yAZBRYyz0VOPDuj1xx+x7e2GHkuvo3bs5JkY9SYhZjwmyTzzo2Ga6x0XCVKf4dTbF+YBzBtUVC2Re0qxyr0rIMoafH7rN3V+iFPPEVU8y6iIT3zyv0mYr+QxPW0SuabsaAEorckUnzCX2jRg+HeOgZ7eKE=
  - secure: v1g1SR19cy8SZL5wW/g0stE4OLUnKYK/2SssgymCL2EEzeJjAPLl52LHjEKcN1+vPD1DNLoyf/nOax6dlll6X64RfyEmAu24bkYTHegAYJjM03PJ6HBH7MY9HHDsQYDWZY1yJgAxE+oxjG/giqI4Iuoq1OplqMmaFkjX3KAeQU+thdlK9yKruVOPatAPcsen43PyT1bog9jg2bjPSdWNYaPMnsUdPMLLa4jzds22ehIVeDDHuPNhBadG4N+rX0ItqbYMdyWMUbUsZtAs0+dGVcRg5y+We3fFnP7pkiY/yek/KjC4gVyW49r/M9WjSVDWf2WNUNKAmM28BRCTbScGZBwPHgXPUVi7O+pqJVT3KPZngo1ItFK1KbGq8bxqi+ZoRbnhgD1D2xoWdCDDiJrpqMruLPH7A1YTfttAvHPYgjPTzyurVxCUXCKc4tcVOhAUrggKqAv4deEDlLuaVTow6CQ+NYsQK9UAGpTGa9anidqEjJXqVisBPCB91KCLiVwutWPG9PwqI6urnFNuxAMST8oHcA6dBOmZCTiIIDCoE8FLJcRmbqvkWKvJBqy9LG8BOkzsImbeMywL5LjhsfeunITwCoDnbFpPYPX1Zff3KEGDSgjRAOt6PlBGJ+2eIqnYTqqObGnlhOhbHj9VEUojc/4NWBi9b6rDiynK2J4wDhY=
