name: Python Package CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install ".[test]"

    - name: Lint with black
      run: |
        black --check .
    
    - name: Run tests
      run: |
        pytest tests/*.py

    - name: Build package
      run: |
        python -m pip install wheel
        python setup.py sdist bdist_wheel